name: Deploy on Now
on: push
  branches:
  - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Print GitHub Context # Debug step
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: release
      uses: actions/zeit-now@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        
